services:
  db:
    image: mysql:${MYSQL_VERSION:-9.3}
    restart: unless-stopped
    environment:
      MYSQL_DATABASE: ${MYSQL_DATABASE:-tipped}
      MYSQL_USER: ${MYSQL_USER:-tipped_user}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD:-tipped_password}
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD:-tipped_root_password}
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: