services:
  db:
    image: mysql:${MYSQL_VERSION:-9.3}
    restart: unless-stopped
    env_file:
      - .env.docker
    ports:
      - "${MYSQL_PORT:-3306}:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data: