---
kind: pipeline
type: docker
name: default

steps:
  - name: test
    image: node:24
    when:
      event:
        - push
        - pull_request
    commands:
      - corepack enable pnpm
      - pnpm install
      - pnpm test

  - name: slack
    image: plugins/slack
    when:
      event:
        - push
        - pull_request
    settings:
      webhook:
        from_secret: slack-webhook-url
